apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: geoip-https
  name: geoip-https
  namespace: osg-services
spec:
  selector:
    matchLabels:
      k8s-app: geoip-https
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: geoip-https
    spec:
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/stashcache
        operator: Exists
      containers:
      - image: aaarora/geoip-http:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        name: geoip-https
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 1
            memory: 2Gi
        volumeMounts:
        - mountPath: /home/GeoIP
          name: cache-vol
        - mountPath: /code/geoip.py
          name: geoip-https
          subPath: geoip.py
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: stashcache.t2.ucsd.edu
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cache-vol
        emptyDir: {}
      - name: geoip-https
        configMap:
          name: geoip-https
          items:
          - key: geoip.py
            path: geoip.py
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: geoip-https-hpa
  namespace: osg-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: geoip-https
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Object
    object:
      metric:
        name: requests-per-second
      describedObject:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        name: geoip-https-ing
      target:
        type: Value
        value: 5k
