resources:
  - deploy.yaml
  - svc.yaml

configMapGenerator:
  - name: geoip-https
    files:
      - geoip.py

generatorOptions:
  disableNameSuffixHash: true

namespace: osg-services

commonLabels:
  k8s-app: geoip-https
